### PR TITLE
Prevent usage of 'in' with non-readonly structs by a compiler error

### PR DESCRIPTION
**Pull request by dymanoid**
Using a Roslyn Analyzer [ReflectionIT.Analyzer.Structs](https://www.nuget.org/packages/ReflectionIT.Analyzer.Structs/), issue a compiler error when a non-`readonly` struct is passed to a method using the `in` modifier.

Passing a non-readonly struct with an `in` modifier can drastically decrease performance, because in the called method, the compiler will create defensive struct copies on every method call or property access of that passed struct.

Closes krzychu124/Cities-Skylines-Traffic-Manager-President-Edition#440.

### CODE REVIEW

**Comment by krzychu124** [comment]
Works only with `VS 2019` because of missing dependency `Microsoft.CodeAnalysis, Version=3.1.0.0` 😕

**Comment by dymanoid** [comment]
Okay, didn't know you're on VS2017. Should I fork that analyzer and downgrade it back to VS2017 toolset, or you prefer to upgrade your IDE?

**Comment by krzychu124** [comment]
I've upgraded my IDE 😃 
I've had to change environment in AppVeyor to VS2019. Downside of that is longer queue for build 😕

**Comment by aubergine10** [comment]
Updated dev tools wiki page to note VS 2019 requirement: https://github.com/krzychu124/Cities-Skylines-Traffic-Manager-President-Edition/wiki/Dev-Tools

I assume it works on Rider too?

Will this also work on Visual Studio Code - I think @FireController1847 was using that for EVE dev.

**Comment by kvakvs** [comment]
Clean and rebuild in both FullDebug and Release, worked on Rider with no visible effect.

**Comment by dymanoid** [comment]
Maybe try to pass a non-readonly `struct` via `in` and see if that leads to a compile error?

**Comment by krzychu124** [comment]
Works on Rider 2019.1.3 but only while building project/solution. I will check 2019,2 Early Access Preview

**Comment by dymanoid** [comment]
On Rider, you need to explicitly enable Roslyn Analyzers somewhere in the settings. If I recall that correctly.

**Comment by aubergine10** [comment]
Regarding activating the Roslyn Analyzers on Rider, post some details in a comment and I'll  update wiki. I think the two Build guides will also need updating.

**Comment by dymanoid** [comment]
https://www.jetbrains.com/help/rider/Settings_Roslyn_Analyzers.html

**Comment by krzychu124** [comment]
I wanted to add screenshot but I couldn't upload due to timeout to GitHub Amazon S3 server 😄

**Comment by aubergine10** [comment]
Ah, the .dll has to be manually downloaded?
```
1>CSC : error CS0006: Metadata file '..\packages\ReflectionIT.Analyzer.Structs.0.1.0\analyzers\dotnet\cs\ReflectionIT.Analyzer.Structs.dll' could not be found
```

**Comment by dymanoid** [comment]
No, the NuGet package manager should automatically restore the packages and download the binaries.

**Comment by aubergine10** [comment]
Looks like I built before it finished downloading lol. It's working now. I've not tested non-readonly structs and the `in` keyword yet.

**Comment by dymanoid** [comment]
This is not possible. The Analyzer will generate a compiler error, so the code won't compile and the unit test cannot be run. If the code compiles though and the test executes, that means the Analyzer doesn't work.

**Comment by krzychu124** [comment]
@aubergine10 what do you think? Looks good to me.
Can we merge it?

**Comment by krzychu124** [comment]
I did a few tests
It's easy, look 😉 
Method:
```cs
private void Test(in Vector2 vec){
    Debug.Log(vec); // whatever
}
```
Call 
```cs
Vector2 vec = new Vector2(1f, 1f);
Test(vec); //this line should create compilation error because Vector2 is not readonly struct
```

**Comment by aubergine10** [comment]
👍
